defmodule Gongu.Repo.Migrations.AddInviteCodeToGroups do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:groups) do
      add :invite_code, :text
    end

    create unique_index(:groups, [:invite_code], name: "groups_unique_invite_code_index")
  end

  def down do
    drop_if_exists unique_index(:groups, [:invite_code], name: "groups_unique_invite_code_index")

    alter table(:groups) do
      remove :invite_code
    end
  end
end
