defmodule Gongu.Repo.Migrations.AddCalendarsAndEvents do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:events, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :title, :text, null: false
      add :description, :text
      add :start_time, :utc_datetime, null: false
      add :end_time, :utc_datetime, null: false
      add :all_day, :boolean, null: false, default: false
      add :location, :text
      add :calendar_id, :uuid, null: false
      add :recurrence_rule, :text
      add :status, :text, null: false, default: "confirmed"
      add :created_by_id, :uuid, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:calendars, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:events) do
      modify :calendar_id,
             references(:calendars,
               column: :id,
               name: "events_calendar_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :created_by_id,
             references(:users,
               column: :id,
               name: "events_created_by_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:calendars) do
      add :name, :text, null: false
      add :description, :text
      add :color, :text, default: "#4285f4"
      add :timezone, :text, default: "Asia/Seoul"
      add :visibility, :text, null: false, default: "private"

      add :owner_id,
          references(:users,
            column: :id,
            name: "calendars_owner_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :group_id,
          references(:groups,
            column: :id,
            name: "calendars_group_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:calendars, [:name, :owner_id],
             name: "calendars_unique_name_per_owner_index"
           )
  end

  def down do
    drop_if_exists unique_index(:calendars, [:name, :owner_id],
                     name: "calendars_unique_name_per_owner_index"
                   )

    drop constraint(:calendars, "calendars_owner_id_fkey")

    drop constraint(:calendars, "calendars_group_id_fkey")

    alter table(:calendars) do
      remove :updated_at
      remove :inserted_at
      remove :group_id
      remove :owner_id
      remove :visibility
      remove :timezone
      remove :color
      remove :description
      remove :name
    end

    drop constraint(:events, "events_calendar_id_fkey")

    drop constraint(:events, "events_created_by_id_fkey")

    alter table(:events) do
      modify :created_by_id, :uuid
      modify :calendar_id, :uuid
    end

    drop table(:calendars)

    drop table(:events)
  end
end
