defmodule Gongu.Repo.Migrations.AddInvitationsAndRemoveInviteCode do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:invitations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :code, :text, null: false

      add :group_id,
          references(:groups,
            column: :id,
            name: "invitations_group_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :created_by_id,
          references(:users,
            column: :id,
            name: "invitations_created_by_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :status, :text, null: false, default: "pending"
      add :expires_at, :utc_datetime_usec, null: false
      add :used_at, :utc_datetime_usec

      add :used_by_id,
          references(:users,
            column: :id,
            name: "invitations_used_by_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:invitations, [:code], name: "invitations_unique_code_index")

    alter table(:groups) do
      remove :invite_code
    end

    drop_if_exists unique_index(:groups, [:invite_code], name: "groups_unique_invite_code_index")
  end

  def down do
    create unique_index(:groups, [:invite_code], name: "groups_unique_invite_code_index")

    alter table(:groups) do
      add :invite_code, :text
    end

    drop_if_exists unique_index(:invitations, [:code], name: "invitations_unique_code_index")

    drop constraint(:invitations, "invitations_group_id_fkey")

    drop constraint(:invitations, "invitations_created_by_id_fkey")

    drop constraint(:invitations, "invitations_used_by_id_fkey")

    drop table(:invitations)
  end
end
